version: '3.9'
services:
  nginx:
#    image: nginx:1.21-alpine
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    #entrypoint: /bin/sh
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
    volumes:
      - ./nginx/etc/includes:/etc/nginx/includes:ro
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template:ro
      - ./html:/var/www/html:ro
      - ./data/nginx/certbot/www:/var/www/certbot:ro
      - ./data/nginx/certbot/conf:/etc/letsencrypt:rw
      - /home:/home:ro
    env_file:
      - env.production

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/nginx/certbot/conf:/etc/letsencrypt
      - ./data/nginx/certbot/www:/var/www/certbot
