apiVersion: 1
datasources:
  - name: Prometheus
    version: 2
    orgId: 1
    uid: 5qpBRfD4k
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData: 
        httpMethod: POST
