version: "3"

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.16.6
    env_file:
      - ../env.production
      - env.production
      - ../data/gitea/env.secrets
    environment:
      - USER_UID=2222 # must match git user on host system
      - USER_GID=2222
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    networks:
      - gitea
    volumes:
      - ../data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh/:/data/git/.ssh
    ports:
      - "3030:3000"
      - "2222:22"
    restart: always
    depends_on:
      - db
 
  db:
    image: postgres:13.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ../data/gitea/postgres:/var/lib/postgresql/data
    networks:
      - gitea
