#!/bin/bash
die() { echo >&2 "$@" ; exit 1 ; }

client_name="$1"
hostname="$2"
secret="$3"

client_id="$(kcadm.sh get clients \
	-r "$REALM" \
	--fields id \
	-q clientId="$client_name" \
	--format csv \
	--noquotes \
)"

if [ -n "$client_id" ]; then
	kcadm.sh delete "clients/$client_id" -r "$REALM" || die "$client_id: unable to delete"
fi

# remember to add a leading , if adding extra data
extra="$(cat -)"

kcadm.sh create clients -r "$REALM"  -f - <<EOF || die "$client_id: unable to create"
{
	"clientId": "$client_name",
	"rootUrl": "https://$hostname",
	"adminUrl": "https://$hostname",
	"redirectUris": [ "https://$hostname/*" ],
	"webOrigins": [ "https://$hostname" ],
	"clientAuthenticatorType": "client-secret",
	"secret": "$secret"
	$extra
}
EOF
