version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:5.7
      volumes:
        - ./data/database:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password

  keycloak:
      image: quay.io/keycloak/keycloak:18.0.0
      entrypoint: /opt/keycloak/bin/kc.sh start-dev --proxy=edge
      env_file:
        - ../env.production
        - env.production
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        PROXY_ADDRESS_FORWARDING: 'true'
      volumes:
        - ./data/certs:/etc/x509/https
      ports:
        - 8080:8080
        - 8443:8443
      depends_on:
        - mysql
