{
 "title": "Synapse",
 "description": "Synapse dashboard from https://github.com/matrix-org/synapse/blob/master/contrib/grafana/synapse.json",
 "tags": [ "matrix" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "bucket_size", "label": "Bucket Size", "query": "30s,1m,2m,5m,10m,15m" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(synapse_util_metrics_block_ru_utime_seconds, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(synapse_util_metrics_block_ru_utime_seconds, job)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(synapse_util_metrics_block_ru_utime_seconds, index)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
     "legendFormat": "{{job}}-{{index}} "
    }
   ]
  },
  {
   "title": "Event Send Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\"}[$bucket_size])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Events Persisted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(synapse_storage_events_persisted_events{instance=\"$instance\"}[$bucket_size])) without (job,index)"
    }
   ]
  },
  {
   "title": "Process info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}} {{index}}"
      }
     ]
    },
    {
     "title": "Open FDs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Avg reactor tick time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(python_twisted_reactor_tick_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(python_twisted_reactor_tick_time_count[$bucket_size])",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Reactor tick quantiles",
     "type": "graph",
     "description": "Shows the time in which the given percentage of reactor ticks completed, over the sampled timespan",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(python_twisted_reactor_tick_time_bucket{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, rate(python_twisted_reactor_tick_time_bucket{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} 95%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(python_twisted_reactor_tick_time_bucket{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} 90%"
      },
      {}
     ]
    },
    {
     "title": "Up",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min_over_time(up{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Prometheus scrape time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "scrape_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_system_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} system "
      },
      {
       "expr": "rate(process_cpu_user_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} user"
      }
     ]
    }
   ]
  },
  {
   "title": "Event persist rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events/s Local vs Remote",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_source_type{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Events/s by Type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_event_type{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Events/s by Origin",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_origin{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{origin_entity}} ({{origin_type}})"
      }
     ]
    },
    {
     "title": "Memberships/s by Origin",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_storage_events_persisted_events_sep{job=~\"$job\",index=~\"$index\", type=\"m.room.member\",instance=\"$instance\"}[$bucket_size])) by (origin_type, origin_entity)",
       "legendFormat": "{{origin_entity}} ({{origin_type}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count by arrival time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_requests_received{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "Top 10 Request Counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_requests_received{instance=\"$instance\",job=~\"$job\",index=~\"$index\",method!=\"OPTIONS\"}[$bucket_size]) and topk(10,synapse_http_server_requests_received{instance=\"$instance\",job=~\"$job\",method!=\"OPTIONS\"})",
       "legendFormat": "{{method}} {{servlet}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Total CPU Usage by Endpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_response_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_http_server_response_ru_stime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "Average CPU Usage by Endpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(synapse_http_server_response_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_http_server_response_ru_stime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) / rate(synapse_http_server_response_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "DB Usage by endpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_response_db_txn_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "Non-sync avg response time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_response_time_seconds_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\",tag!=\"incremental_sync\"}[$bucket_size])/rate(synapse_http_server_response_time_seconds_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\",tag!=\"incremental_sync\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "Requests in flight",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,synapse_http_server_in_flight_requests_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"})",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage by background jobs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_background_process_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_background_process_ru_stime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "DB usage by background jobs (including scheduling time)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_background_process_db_txn_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) +  rate(synapse_background_process_db_sched_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Federation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing federation transaction rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_federation_client_sent_transactions{instance=\"$instance\", job=~\"$job\", index=~\"$index\"}[$bucket_size])",
       "legendFormat": "txn rate"
      }
     ]
    },
    {
     "title": "Incoming PDU/EDU rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_federation_server_received_pdus{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "pdus"
      },
      {
       "expr": "rate(synapse_federation_server_received_edus{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "edus"
      }
     ]
    }
   ]
  },
  {
   "title": "Pushes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Push rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_push_httppusher_http_pushes_processed{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "processed {{job}}"
      },
      {
       "expr": "rate(synapse_push_httppusher_http_pushes_failed{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "failed {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg time waiting for db conn",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_schedule_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(synapse_storage_schedule_time_count[$bucket_size])",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Db scheduling time quantiles",
     "type": "graph",
     "description": "Shows the time in which the given percentage of database queries were scheduled, over the sampled timespan",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 95%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 90%"
      }
     ]
    },
    {
     "title": "Top DB transactions by txn rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(synapse_storage_transaction_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} {{desc}}"
      }
     ]
    },
    {
     "title": "Top DB transactions by total txn time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_transaction_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{desc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per-block metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU Usage by Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\",block_name!=\"wrapped_request_handler\"}[$bucket_size]) + rate(synapse_util_metrics_block_ru_stime_seconds[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average CPU Time per Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(rate(synapse_util_metrics_block_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) + rate(synapse_util_metrics_block_ru_stime_seconds[$bucket_size])) / rate(synapse_util_metrics_block_count[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Total DB Usage by Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_db_txn_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\",block_name!=\"wrapped_request_handler\"}[$bucket_size])",
       "legendFormat": "{{job}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average Database Time per Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_db_txn_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) / rate(synapse_util_metrics_block_db_txn_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average Transactions per Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_db_txn_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) / rate(synapse_util_metrics_block_db_txn_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average Wallclock Time per Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_time_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) / rate(synapse_util_metrics_block_count[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_caches_cache:hits{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])/rate(synapse_util_caches_cache:total{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Cache Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_util_caches_cache:size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Cache request rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_caches_cache:total{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Top 10 cache misses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(synapse_util_caches_cache:total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size]) - rate(synapse_util_caches_cache:hits{job=\"$job\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Cache eviction rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "hertz", "label": "entries / second" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_caches_cache:evicted_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total GC time by bucket (10m smoothing)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[10m])",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "Average GC Time Per Collection",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_time_sum{instance=\"$instance\",job=~\"$job\"}[$bucket_size])/rate(python_gc_time_count[$bucket_size])",
       "legendFormat": "{{job}} {{index}} gen {{gen}} "
      }
     ]
    },
    {
     "title": "Currently allocated objects",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "python_gc_counts{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "Object counts per collection",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_unreachable_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(python_gc_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "GC frequency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "GC durations",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(python_gc_time_bucket[$bucket_size])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of events on replication master",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_replication_tcp_resource_user_sync{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "user started/stopped syncing"
      },
      {
       "expr": "rate(synapse_replication_tcp_resource_federation_ack{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "federation ack"
      },
      {
       "expr": "rate(synapse_replication_tcp_resource_remove_pusher{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "remove pusher"
      },
      {
       "expr": "rate(synapse_replication_tcp_resource_invalidate_cache{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "invalidate cache"
      },
      {
       "expr": "rate(synapse_replication_tcp_resource_user_ip_cache{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "user ip cache"
      }
     ]
    },
    {
     "title": "Outgoing stream updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_replication_tcp_resource_stream_updates{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{stream_name}}"
      }
     ]
    },
    {
     "title": "Rate of incoming commands",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum (rate(synapse_replication_tcp_protocol_inbound_commands{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (name, conn_id)",
       "legendFormat": "{{job}}-{{index}} {{command}}"
      }
     ]
    },
    {
     "title": "Rate of outgoing commands",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum (rate(synapse_replication_tcp_protocol_outbound_commands{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (name, conn_id)",
       "legendFormat": "{{job}}-{{index}} {{command}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Event processing loop positions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event processing lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "events" }
     ],
     "targets": [
      {
       "expr": " synapse_event_persisted_position{instance=\"$instance\",job=\"synapse\"}  - ignoring(index, job, name) group_right() synapse_event_processing_positions{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}}-{{index}} "
      }
     ]
    },
    {
     "title": "Age of last processed event",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "time()*1000-synapse_event_processing_last_ts{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    }
   ]
  }
 ]
}