version: "3"

services:
  database:
    image: postgres:13.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
    volumes:
      - ../data/nextcloud/database:/var/lib/postgresql/data

  nextcloud:
    image: nextcloud:23.0.4
    restart: always
    ports:
      - 9000:80
    env_file:
      - ../env.production
      - env.production
      - ../data/nextcloud/env.secrets
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      OVERWRITEPROTOCOL: https
      NEXTCLOUD_ADMIN_USER: admin
      # NEXTCLOUD_ADMIN_PASSWORD in env.secrets
      # NEXTCLOUD_TRUSTED_DOMAINS also set in env.secrets
    volumes:
      - ../data/nextcloud/nextcloud:/var/www/html
    depends_on:
      - database

