version: "3"

services:
  mobilizon:
    image: framasoft/mobilizon
    restart: always
    env_file:
      - ../env.production
      - ./env.production
      - ../data/mobilizon/env.secrets
    volumes:
      - ../data/mobilizon/uploads:/var/lib/mobilizon/uploads
      - ./config.exs:/etc/mobilizon/config.exs:ro
      # - ${PWD}/GeoLite2-City.mmdb:/var/lib/mobilizon/geo_db/GeoLite2-City.mmdb
    ports:
      - "7000:7000"

  db:
    image: postgis/postgis:13-3.1
    restart: always
    volumes:
      - ../data/mobilizon/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mobilizon
      - POSTGRES_PASSWORD=mobilizon
      - POSTGRES_DB=mobilizon
